//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources.AdminPaneli.Uyeler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Uyeler {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Uyeler() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.AdminPaneli.Uyeler.Uyeler", typeof(Uyeler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string Adı {
            get {
                return ResourceManager.GetString("Adı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Düzenle.
        /// </summary>
        public static string adminduzenle {
            get {
                return ResourceManager.GetString("adminduzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Ekle.
        /// </summary>
        public static string adminekle {
            get {
                return ResourceManager.GetString("adminekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminleri Göster.
        /// </summary>
        public static string admingoster {
            get {
                return ResourceManager.GetString("admingoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Sil.
        /// </summary>
        public static string Adminsil {
            get {
                return ResourceManager.GetString("Adminsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string eklebutton {
            get {
                return ResourceManager.GetString("eklebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail adresi.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string Kullanıcı {
            get {
                return ResourceManager.GetString("Kullanıcı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrencileri Göster.
        /// </summary>
        public static string ogrencibaslik {
            get {
                return ResourceManager.GetString("ogrencibaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Düzenle.
        /// </summary>
        public static string ogrenciduzenle {
            get {
                return ResourceManager.GetString("ogrenciduzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Ekle.
        /// </summary>
        public static string ogrenciekle {
            get {
                return ResourceManager.GetString("ogrenciekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenicileri Goster.
        /// </summary>
        public static string ogrencigoster {
            get {
                return ResourceManager.GetString("ogrencigoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Sil.
        /// </summary>
        public static string ogrenciSil {
            get {
                return ResourceManager.GetString("ogrenciSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmenleri Göster.
        /// </summary>
        public static string ogretmenbaslik {
            get {
                return ResourceManager.GetString("ogretmenbaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Duzenle.
        /// </summary>
        public static string ogretmenduzenle {
            get {
                return ResourceManager.GetString("ogretmenduzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Ekle.
        /// </summary>
        public static string ogretmenekle {
            get {
                return ResourceManager.GetString("ogretmenekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmenleri Göster.
        /// </summary>
        public static string ogretmengoster {
            get {
                return ResourceManager.GetString("ogretmengoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Sil.
        /// </summary>
        public static string ogretmenSil {
            get {
                return ResourceManager.GetString("ogretmenSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrarı.
        /// </summary>
        public static string Sifretekrari {
            get {
                return ResourceManager.GetString("Sifretekrari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        public static string Soyadi {
            get {
                return ResourceManager.GetString("Soyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Öğrenci Oluştur.
        /// </summary>
        public static string yeniögrenci {
            get {
                return ResourceManager.GetString("yeniögrenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Öğretmen Oluştur.
        /// </summary>
        public static string yeniogretmen {
            get {
                return ResourceManager.GetString("yeniogretmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkisi.
        /// </summary>
        public static string yetki {
            get {
                return ResourceManager.GetString("yetki", resourceCulture);
            }
        }
    }
}
