//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources.AdminPaneli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menüler {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menüler() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.AdminPaneli.Menüler", typeof(Menüler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Sayfasına Hoşgeldiniz.
        /// </summary>
        public static string adminAnasayfa {
            get {
                return ResourceManager.GetString("adminAnasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Paneli.
        /// </summary>
        public static string AdminPaneli {
            get {
                return ResourceManager.GetString("AdminPaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döküman Sayfasını Görüntüle.
        /// </summary>
        public static string DokumanGoruntu {
            get {
                return ResourceManager.GetString("DokumanGoruntu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döküman Sayfası İşlemleri.
        /// </summary>
        public static string Dokumansayfasi {
            get {
                return ResourceManager.GetString("Dokumansayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Ekle.
        /// </summary>
        public static string DosyaEkle {
            get {
                return ResourceManager.GetString("DosyaEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Ekle.
        /// </summary>
        public static string DuyuruEkle {
            get {
                return ResourceManager.GetString("DuyuruEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci.
        /// </summary>
        public static string Ogrenci {
            get {
                return ResourceManager.GetString("Ogrenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Dosya Yorumları.
        /// </summary>
        public static string ogrencidosyayorumları {
            get {
                return ResourceManager.GetString("ogrencidosyayorumları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Dosya Yorumları.
        /// </summary>
        public static string ogretmendosyayorumları {
            get {
                return ResourceManager.GetString("ogretmendosyayorumları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen.
        /// </summary>
        public static string Ogretmenler {
            get {
                return ResourceManager.GetString("Ogretmenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyeler.
        /// </summary>
        public static string Uyeler {
            get {
                return ResourceManager.GetString("Uyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string Yorumlar {
            get {
                return ResourceManager.GetString("Yorumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziyaretci Yorumları.
        /// </summary>
        public static string ziyaretciyorumları {
            get {
                return ResourceManager.GetString("ziyaretciyorumları", resourceCulture);
            }
        }
    }
}
