//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dokumanlar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dokumanlar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.Dokumanlar", typeof(Dokumanlar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖKÜMANLAR VE DOSYALAR.
        /// </summary>
        public static string dokumanbaslik {
            get {
                return ResourceManager.GetString("dokumanbaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Aciklama.
        /// </summary>
        public static string dosyaaciklama {
            get {
                return ResourceManager.GetString("dosyaaciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Adı.
        /// </summary>
        public static string dosyaadi {
            get {
                return ResourceManager.GetString("dosyaadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Gönderen.
        /// </summary>
        public static string dosyagönderenkisi {
            get {
                return ResourceManager.GetString("dosyagönderenkisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Konusu.
        /// </summary>
        public static string dosyakonu {
            get {
                return ResourceManager.GetString("dosyakonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Tarihi.
        /// </summary>
        public static string dosyatarihi {
            get {
                return ResourceManager.GetString("dosyatarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indir.
        /// </summary>
        public static string indirmekısmı {
            get {
                return ResourceManager.GetString("indirmekısmı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAPAT.
        /// </summary>
        public static string kapat {
            get {
                return ResourceManager.GetString("kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖKÜMAN VE DOSYA SAYFASI.
        /// </summary>
        public static string pdfsayfasi {
            get {
                return ResourceManager.GetString("pdfsayfasi", resourceCulture);
            }
        }
    }
}
