//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Giriş.
        /// </summary>
        public static string admingiris {
            get {
                return ResourceManager.GetString("admingiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANASAYFA.
        /// </summary>
        public static string ANASAYFA {
            get {
                return ResourceManager.GetString("ANASAYFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğru Pdf Önemlidir.
        /// </summary>
        public static string DoğruPdfÖnemlidir {
            get {
                return ResourceManager.GetString("DoğruPdfÖnemlidir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsanların kullanımlarını kolaylaştırmak ve istedikleri belgelere rahat bir şekilde ulaşabilmelerini sağlamak amacı ile oluşturulmuşlardır. Bunun yanı sıra, böyle dosyaları hazırlamak isteyen ve belge olarak sanal ortama taşımak isteyen kişiler için de oldukça vazgeçilmez olmuşlardır.
        ///
        ///.
        /// </summary>
        public static string DoğruPdfÖnemlidirbilg2 {
            get {
                return ResourceManager.GetString("DoğruPdfÖnemlidirbilg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyalar için bilgisayar kullanımı başladığından beri farklı formatlar vardır. Bu formatlar zaman içerisinde gelişmekte ve buna ek olarak yenileri de çıkmaktadır.
        ///
        ///.
        /// </summary>
        public static string DoğruPdfÖnemlidirbilgi1 {
            get {
                return ResourceManager.GetString("DoğruPdfÖnemlidirbilgi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzun yıllardan beri çok sayıda farklı belgenin oluşturulmasını ve korunmasını sağlayan uzantılardan birisi de PDF ‘dir. PDF İngilizce Portable Document Format yani taşınabilir belge biçimi demektir. Bu uzantıya sahip olan dosyaları günümüzde çok sayıda kişi kullanır. Aynı zamanda resmi yerlerde de kullanımları söz konusu olduğu için bir hayli öneme sahiptir ve günümüzde vazgeçilmez bir hal almıştır. PDF dosyalarının en önemli avantajlarından biri orijinal dökümanda kullanılan tüm yazı karakterlerini, vektör [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DoğruPdfÖnemlidirbilgi3 {
            get {
                return ResourceManager.GetString("DoğruPdfÖnemlidirbilgi3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖKÜMANLAR.
        /// </summary>
        public static string DÖKÜMANLAR {
            get {
                return ResourceManager.GetString("DÖKÜMANLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Aciklama.
        /// </summary>
        public static string duyuruaciklama {
            get {
                return ResourceManager.GetString("duyuruaciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Adi.
        /// </summary>
        public static string duyuruadi {
            get {
                return ResourceManager.GetString("duyuruadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyurular.
        /// </summary>
        public static string duyurubaslik {
            get {
                return ResourceManager.GetString("duyurubaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Tarihi.
        /// </summary>
        public static string DuyuruTarihi {
            get {
                return ResourceManager.GetString("DuyuruTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitimin Önemi.
        /// </summary>
        public static string EğitiminÖnemi {
            get {
                return ResourceManager.GetString("EğitiminÖnemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitimsiz kişiler gerek topluma gerekse kendisine zararı olanlar insanlardır. Toplumdaki suçların büyük çoğunluğu eğitim ve öğretim görmemiş kişiler tarafından işlenmektedir. Buradaki eğitimi sadece okumakla sınırlandırmamak gerekmektedir.….
        /// </summary>
        public static string EğitiminÖnemibilgi {
            get {
                return ResourceManager.GetString("EğitiminÖnemibilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gerekmektedir..
        /// </summary>
        public static string gerekmektedir {
            get {
                return ResourceManager.GetString("gerekmektedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKIMIZDA.
        /// </summary>
        public static string HAKKIMIZDA {
            get {
                return ResourceManager.GetString("HAKKIMIZDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1998 yılında &quot;En yeni iletişim ve bilgisayar teknolojilerini kullanarak müşterilerine dünya standartlarında çözümler sunmak&quot; ilkesiyle yola çıkan isimtescil.net, geçen 16 yıllık süreçte Dünya ve Türkiye’ye, en büyük domain ve hosting firmalarından biri olmayı başarmıştır. 2008 yılında alan adları standartlarını belirleyen ve denetleyen tek otorite ICANN&apos;e akredite olan isimtescil.net, 2010 yılından beri Türkiye&apos;nin en büyük 500 bilişim şirketi arasında yer almakta ve kurulduğu günden buyana 1 milyonun üzeri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string hakkımızdaSayfası1 {
            get {
                return ResourceManager.GetString("hakkımızdaSayfası1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 kişilik ekibi ile 7/24 destek operasyonunu sürdüren ve sürekli Ar-Ge politikası ile kendi altyapı yatırımlarını yöneten isimtescil.net, 2013 yılında Türkiye&apos;de ilk kez yeni domain uzantıları için ön talep sürecini başlatmış ve bu süreçte 1 milyonun üzerinde talep toplayarak Afrika, Asya ve Doğu Avrupada en fazla talep toplayan şirket ünvanını almıştır. isimtescil.net aynı zamanda .tr uzantılarının Türkiye’deki yetkili operatörlerinden biridir. .tr uzantılı domain kaydediciler arasında en fazla işlem hacm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string hakkımızdaSayfası2 {
            get {
                return ResourceManager.GetString("hakkımızdaSayfası2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM.
        /// </summary>
        public static string İLETİŞİM {
            get {
                return ResourceManager.GetString("İLETİŞİM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ DOSYA GİRİŞİ.
        /// </summary>
        public static string ogrencidosyagirisi {
            get {
                return ResourceManager.GetString("ogrencidosyagirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ GİRİŞ.
        /// </summary>
        public static string ogrencigiris {
            get {
                return ResourceManager.GetString("ogrencigiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci girişi yapmak için
        ///.
        /// </summary>
        public static string ogrencigirisbilgi {
            get {
                return ResourceManager.GetString("ogrencigirisbilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRETMEN DOSYA GİRİŞİ.
        /// </summary>
        public static string ogretmendosyagirisi {
            get {
                return ResourceManager.GetString("ogretmendosyagirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖGRETMEN GİRİŞ.
        /// </summary>
        public static string ogretmengiris {
            get {
                return ResourceManager.GetString("ogretmengiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen girişi yapmak için
        ///.
        /// </summary>
        public static string ogretmengirisibilgi {
            get {
                return ResourceManager.GetString("ogretmengirisibilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teknoloji.
        /// </summary>
        public static string Teknoloji {
            get {
                return ResourceManager.GetString("Teknoloji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknolojinin gelişimi ile ilgili yazı. Teknolojinin açılımını yapalım önce. Sanat ve bilmek kelimelerinden türemiş bir kelime olan teknoloji, günümüzde en çok kullandığımız ve gündemimizi en çok meşgule den kelimelerden bir tanesidir.….
        /// </summary>
        public static string Teknolojibilgi {
            get {
                return ResourceManager.GetString("Teknolojibilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeknolojiniEğitimdekiYeri.
        /// </summary>
        public static string TeknolojiniEğitimdekiYeri {
            get {
                return ResourceManager.GetString("TeknolojiniEğitimdekiYeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaşadığımız devir artık teknolojiyi her alanda ve en verimli şekilde kullanma devri. Özellikle eğitim, teknolojinin en çok kullanılması gereken alanlardan biri. Çünkü eğitimde teknoloji kullanımı anlamayı kolaylaştırıyor, pek çok konuyu somutlaştırıyor….
        /// </summary>
        public static string TeknolojiniEğitimdekiYeribilgi {
            get {
                return ResourceManager.GetString("TeknolojiniEğitimdekiYeribilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜYEOL.
        /// </summary>
        public static string ÜyeOl {
            get {
                return ResourceManager.GetString("ÜyeOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Olmanız.
        /// </summary>
        public static string ÜyeOlmanız {
            get {
                return ResourceManager.GetString("ÜyeOlmanız", resourceCulture);
            }
        }
    }
}
