//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class İletisim {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal İletisim() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.İletisim", typeof(İletisim).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız Soyadınız.
        /// </summary>
        public static string adınızsoyadınız {
            get {
                return ResourceManager.GetString("adınızsoyadınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail adresini giriniz.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZİYARETCİ İLETİŞİM SAYFASI.
        /// </summary>
        public static string iletisimbaslik {
            get {
                return ResourceManager.GetString("iletisimbaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yöneticiye mesaj atmak için Lütfen mail adresinizi giriniz..
        /// </summary>
        public static string iletisimbilgi {
            get {
                return ResourceManager.GetString("iletisimbilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string mesaj {
            get {
                return ResourceManager.GetString("mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRETMEN İLETİŞİM SAYFASI.
        /// </summary>
        public static string ogretmeniletisimsayfasi {
            get {
                return ResourceManager.GetString("ogretmeniletisimsayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YORUM YAP.
        /// </summary>
        public static string yorumyapbutton {
            get {
                return ResourceManager.GetString("yorumyapbutton", resourceCulture);
            }
        }
    }
}
