//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mesajlar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mesajlar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.Mesajlar", typeof(Mesajlar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Böyle bir Admin bulunmuyor. Admin değilseniz bu sayfadan çıkın..
        /// </summary>
        public static string adminüye {
            get {
                return ResourceManager.GetString("adminüye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcıya ait böyle bir derskodu vardır.Başka bir ders kodu giriniz.
        /// </summary>
        public static string derskoduvarzaten {
            get {
                return ResourceManager.GetString("derskoduvarzaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir derskodu ve kullanıcı yoktur.
        /// </summary>
        public static string derskoduvekullanıcıyoktur {
            get {
                return ResourceManager.GetString("derskoduvekullanıcıyoktur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Başarıyla Eklendi.
        /// </summary>
        public static string dosyabasariylaeklendi {
            get {
                return ResourceManager.GetString("dosyabasariylaeklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Ekleyemediniz bazı hatalardan dolayı.
        /// </summary>
        public static string dosyaekleyemedinizbazıhatalardandolayı {
            get {
                return ResourceManager.GetString("dosyaekleyemedinizbazıhatalardandolayı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Yüklenemedi.
        /// </summary>
        public static string dosyayüklenemedi {
            get {
                return ResourceManager.GetString("dosyayüklenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir kullanıcı adı veya E-mail adresi kullanılıyor..
        /// </summary>
        public static string emailzatenvar {
            get {
                return ResourceManager.GetString("emailzatenvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BU SAYFAYA GİRMEK İÇİN ÜYE OLUNUZ VE GİRİŞ YAPINIZ.
        /// </summary>
        public static string hatabilgi {
            get {
                return ResourceManager.GetString("hatabilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata oluştu tekrar bilgilerinizi giriniz.
        /// </summary>
        public static string hataolustu {
            get {
                return ResourceManager.GetString("hataolustu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir ÖgrenciDosya kullanıcı bulunmuyor. Üye değilseniz lütfen üye olun!.
        /// </summary>
        public static string ogrenciuye {
            get {
                return ResourceManager.GetString("ogrenciuye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir ÖgrenciiDosya kullanıcı bulunmuyor. Üye değilseniz lütfen üye olun!.
        /// </summary>
        public static string ogrenciuyehata {
            get {
                return ResourceManager.GetString("ogrenciuyehata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir üye bulunuyor Lütfen kullanıcı adı veya Emaili değiştirin.
        /// </summary>
        public static string ogretmenhata1 {
            get {
                return ResourceManager.GetString("ogretmenhata1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir öğretmenDosya kullanıcı bulunmuyor.Üye değilseniz lütfen üye olun!.
        /// </summary>
        public static string ogretmenuye {
            get {
                return ResourceManager.GetString("ogretmenuye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir öğretmenDosya kullanıcı bulunmuyor.Üye değilseniz lütfen üye olun!.
        /// </summary>
        public static string ogretmenuyehata {
            get {
                return ResourceManager.GetString("ogretmenuyehata", resourceCulture);
            }
        }
    }
}
