//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UyeOl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UyeOl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.UyeOl", typeof(UyeOl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string adiniz {
            get {
                return ResourceManager.GetString("adiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir seçim yapınız.
        /// </summary>
        public static string biriniseciniz {
            get {
                return ResourceManager.GetString("biriniseciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailadresi.
        /// </summary>
        public static string emailadresi {
            get {
                return ResourceManager.GetString("emailadresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıadi.
        /// </summary>
        public static string kullaniciadi {
            get {
                return ResourceManager.GetString("kullaniciadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci.
        /// </summary>
        public static string öğrenci {
            get {
                return ResourceManager.GetString("öğrenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen.
        /// </summary>
        public static string öğretmen {
            get {
                return ResourceManager.GetString("öğretmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz.
        /// </summary>
        public static string seciniz {
            get {
                return ResourceManager.GetString("seciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifre.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SifreTekrarı.
        /// </summary>
        public static string sifretekrarı {
            get {
                return ResourceManager.GetString("sifretekrarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız.
        /// </summary>
        public static string soyadiniz {
            get {
                return ResourceManager.GetString("soyadiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya paylaşmak için dogru siteye geldiniz..
        /// </summary>
        public static string üyenot1 {
            get {
                return ResourceManager.GetString("üyenot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yapabilmek için Lütfen Üye olunuz.Kullanıcı adınız çok önemlidir..
        /// </summary>
        public static string üyenot2 {
            get {
                return ResourceManager.GetString("üyenot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siteme üye oldugunuz için teşekkürler..
        /// </summary>
        public static string üyenot3 {
            get {
                return ResourceManager.GetString("üyenot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜYE OL.
        /// </summary>
        public static string üyeolbaslik {
            get {
                return ResourceManager.GetString("üyeolbaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle Bir Kullanıcı Adı Veya E-Mail Adresi Kullanılıyor..
        /// </summary>
        public static string uyeolhatamesajı {
            get {
                return ResourceManager.GetString("uyeolhatamesajı", resourceCulture);
            }
        }
    }
}
