//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources.AdminPaneli.Yorumlar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Yorumlar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Yorumlar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.AdminPaneli.Yorumlar.Yorumlar", typeof(Yorumlar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string İçerik {
            get {
                return ResourceManager.GetString("İçerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Dosya Yorum  Detayları.
        /// </summary>
        public static string ogrencidetayyorum {
            get {
                return ResourceManager.GetString("ogrencidetayyorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ögrenci Yorumları.
        /// </summary>
        public static string ogrenciyorumları {
            get {
                return ResourceManager.GetString("ogrenciyorumları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Yorumlarını Gör.
        /// </summary>
        public static string ogrenciyorumlarıgor {
            get {
                return ResourceManager.GetString("ogrenciyorumlarıgor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Yorumlarını Sil.
        /// </summary>
        public static string ogrenciyorumlarısil {
            get {
                return ResourceManager.GetString("ogrenciyorumlarısil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ögretmen Dosya Yorum  Detayları.
        /// </summary>
        public static string ogretmendetayyorum {
            get {
                return ResourceManager.GetString("ogretmendetayyorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Yorumları.
        /// </summary>
        public static string ogretmenyorumları {
            get {
                return ResourceManager.GetString("ogretmenyorumları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Yorumlarını Gör.
        /// </summary>
        public static string ogretmenyorumlarıgor {
            get {
                return ResourceManager.GetString("ogretmenyorumlarıgor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Yorumlarını Sil.
        /// </summary>
        public static string ogretmenyorumlarısil {
            get {
                return ResourceManager.GetString("ogretmenyorumlarısil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziyaretçi Adı.
        /// </summary>
        public static string zAdi {
            get {
                return ResourceManager.GetString("zAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziyaretçi Email.
        /// </summary>
        public static string zemail {
            get {
                return ResourceManager.GetString("zemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziyaretçi Detayları.
        /// </summary>
        public static string ziyaretciDetaylar {
            get {
                return ResourceManager.GetString("ziyaretciDetaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziyaretçi Sil.
        /// </summary>
        public static string ziyaretciSil {
            get {
                return ResourceManager.GetString("ziyaretciSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziyaretçi Yorumları.
        /// </summary>
        public static string ziyaretciYorumlaribaslik {
            get {
                return ResourceManager.GetString("ziyaretciYorumlaribaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziyaretci Yorumları Göster.
        /// </summary>
        public static string ziyaretciyorumlarıgoster {
            get {
                return ResourceManager.GetString("ziyaretciyorumlarıgoster", resourceCulture);
            }
        }
    }
}
