//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources.Modeller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dokuman {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dokuman() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.Modeller.Dokuman", typeof(Dokuman).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanı en az 10 karakter uzunluğunda olmalıdır!.
        /// </summary>
        public static string aciklama_harf {
            get {
                return ResourceManager.GetString("aciklama_harf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokuman Açıklama.
        /// </summary>
        public static string dokumanaciklama {
            get {
                return ResourceManager.GetString("dokumanaciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokuman Adı.
        /// </summary>
        public static string dokumanadi {
            get {
                return ResourceManager.GetString("dokumanadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanı en az 2 karakter uzunluğunda olmalıdır!.
        /// </summary>
        public static string dokumanharf {
            get {
                return ResourceManager.GetString("dokumanharf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyayı Seçiniz.
        /// </summary>
        public static string dosyaseciniz {
            get {
                return ResourceManager.GetString("dosyaseciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderen Kişi.
        /// </summary>
        public static string gonderen {
            get {
                return ResourceManager.GetString("gonderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string konu {
            get {
                return ResourceManager.GetString("konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanı en az 2 karakter uzunluğunda olmalıdır!.
        /// </summary>
        public static string konu_harf {
            get {
                return ResourceManager.GetString("konu_harf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Dosya Açıklamasını giriniz.
        /// </summary>
        public static string reguired_aciklama {
            get {
                return ResourceManager.GetString("reguired_aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Dosya adını giriniz.
        /// </summary>
        public static string reguired_dokuman {
            get {
                return ResourceManager.GetString("reguired_dokuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Adınızı Soyadınızı giriniz.
        /// </summary>
        public static string reguired_gonderen {
            get {
                return ResourceManager.GetString("reguired_gonderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Konu giriniz.
        /// </summary>
        public static string reguired_konu {
            get {
                return ResourceManager.GetString("reguired_konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Tarih Giriniz.
        /// </summary>
        public static string reguired_Tarih {
            get {
                return ResourceManager.GetString("reguired_Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
    }
}
