//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources.OgrenciPaneli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OgrenciSınıfları {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OgrenciSınıfları() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.OgrenciPaneli.OgrenciSınıfları", typeof(OgrenciSınıfları).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster.
        /// </summary>
        public static string dersgoster {
            get {
                return ResourceManager.GetString("dersgoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Kodu Gir.
        /// </summary>
        public static string derskodugir {
            get {
                return ResourceManager.GetString("derskodugir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders kodundaki Dosyalar.
        /// </summary>
        public static string derskodundakidosyalar {
            get {
                return ResourceManager.GetString("derskodundakidosyalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Açıklama.
        /// </summary>
        public static string dosyaaciklama {
            get {
                return ResourceManager.GetString("dosyaaciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Adı.
        /// </summary>
        public static string dosyaadi {
            get {
                return ResourceManager.GetString("dosyaadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya İndir.
        /// </summary>
        public static string dosyaindirme {
            get {
                return ResourceManager.GetString("dosyaindirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Yüklenme Tarihi.
        /// </summary>
        public static string dosyayuklemetarihi {
            get {
                return ResourceManager.GetString("dosyayuklemetarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderen Kişi.
        /// </summary>
        public static string Gonderenkisi {
            get {
                return ResourceManager.GetString("Gonderenkisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indir.
        /// </summary>
        public static string indir {
            get {
                return ResourceManager.GetString("indir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogrenci Dosya Sayfasına Hoşgeldiniz..
        /// </summary>
        public static string ogrencianasayfa {
            get {
                return ResourceManager.GetString("ogrencianasayfa", resourceCulture);
            }
        }
    }
}
