//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources.Girisler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Uye {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Uye() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.Girisler.Uye", typeof(Uye).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMİN GİRİŞİ.
        /// </summary>
        public static string adminbaslik {
            get {
                return ResourceManager.GetString("adminbaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Giriş Sayfasına Hoşgeldiniz..
        /// </summary>
        public static string adminnot1 {
            get {
                return ResourceManager.GetString("adminnot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yapabilmek için Admin&apos;in izni olması gerekir..
        /// </summary>
        public static string adminnot2 {
            get {
                return ResourceManager.GetString("adminnot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ.
        /// </summary>
        public static string girisbutton {
            get {
                return ResourceManager.GetString("girisbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya paylaşmak için dogru siteye geldiniz..
        /// </summary>
        public static string not1 {
            get {
                return ResourceManager.GetString("not1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yapabilmek için Lütfen Üye olunuz ve seçiminizi yapınız.
        /// </summary>
        public static string not2 {
            get {
                return ResourceManager.GetString("not2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siteme üye oldugunuz için teşekkürler..
        /// </summary>
        public static string not3 {
            get {
                return ResourceManager.GetString("not3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ DOSYA GİRİŞİ.
        /// </summary>
        public static string ogrencidosyabaslik {
            get {
                return ResourceManager.GetString("ogrencidosyabaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRETMEN DOSYA GİRİŞİ.
        /// </summary>
        public static string ögretmendosyabaslik {
            get {
                return ResourceManager.GetString("ögretmendosyabaslik", resourceCulture);
            }
        }
    }
}
