//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yolculuk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnaText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnaText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yolculuk.Resources.AnaText", typeof(AnaText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANASAYFA.
        /// </summary>
        public static string ANASAYFA {
            get {
                return ResourceManager.GetString("ANASAYFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Transfer.
        /// </summary>
        public static string Busines_Transfer {
            get {
                return ResourceManager.GetString("Busines_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSINESS TRANSFER.
        /// </summary>
        public static string Business_Transfer {
            get {
                return ResourceManager.GetString("Business_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Saatlerimiz.
        /// </summary>
        public static string calisma_saatlerimiz {
            get {
                return ResourceManager.GetString("calisma_saatlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÜĞÜN HİZMETLERİMİZ.
        /// </summary>
        public static string Dugun_hizmetlerimiz {
            get {
                return ResourceManager.GetString("Dugun_hizmetlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOŞGELDİNİZ AYSEREN TRUZİM SEYAHAT ACENTASINA.
        /// </summary>
        public static string footer_baslik {
            get {
                return ResourceManager.GetString("footer_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYSEREN truzim transfer olarak her zaman müşterilerimize konforlu,huzurlu,rahat bir yolculuk yapmalarını sağlamaktır..
        /// </summary>
        public static string footer_bilgi {
            get {
                return ResourceManager.GetString("footer_bilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük Geziler.
        /// </summary>
        public static string Gunluk_Geziler {
            get {
                return ResourceManager.GetString("Gunluk_Geziler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftalık Turlar.
        /// </summary>
        public static string Haftalik_Turlar {
            get {
                return ResourceManager.GetString("Haftalik_Turlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKIMIZDA.
        /// </summary>
        public static string HAKKIMIZDA {
            get {
                return ResourceManager.GetString("HAKKIMIZDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamen kalite ve müşteri memnuniyeti kriterleri çerçevesinde sunulan AYSEREN TRANSFER Araç Hizmetlerinde, hizmetinize sunduğumuz araçlarımız yüksek kalite standartlarında donatılmıştır..
        /// </summary>
        public static string Hakkimizda_bilgi_1 {
            get {
                return ResourceManager.GetString("Hakkimizda_bilgi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araçlarımızın kapasitesi dört ve sekiz kişiliktir. AYSEREN TRANSFER araçlarında geçireceğiniz yolculukla unutulmayacak zevki yaşayacaksınız..
        /// </summary>
        public static string Hakkimizda_bilgi_2 {
            get {
                return ResourceManager.GetString("Hakkimizda_bilgi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYSEREN TRANSFER Araç Hizmetlerinde hizmetinizde olacak personelimiz, kadromuzun en seçkin şoförlerinden seçilmiş olup, hizmetinizde hiçbir detayı göz ardı etmeyecek, müşterilerimize &quot;kusursuz hizmet&quot; sunacaklardır..
        /// </summary>
        public static string Hakkimizda_bilgi_3 {
            get {
                return ResourceManager.GetString("Hakkimizda_bilgi_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerli ve yabancı tüm ziyaretçilerimizin ulaşım sorunları ile karşılaşmamaları, güvenli ve doğru güzergahlarla sizi rahat ettirmek için tüm imkanlarımızı seferber ediyoruz. Yurtiçi ve yurtdışı gezilerinizde, organizasyonlarınızda, deneyimli personelimizle, size uygun araçlarımızla hizmetinizdeyiz. Ulaşımda yaşanan zorluklar, günümüzün en önemli sorunlarındandır. Toplu halde seyahat etmek bireyler için gidilecek yere ulaşmak birkaç vasıta değiştirmek zorunda kalınması yorucu olmanın yanı sıra ekonomik anlamda [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Hakkimizda_bilgi_4 {
            get {
                return ResourceManager.GetString("Hakkimizda_bilgi_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYSEREN TRANSFER olarak gerçekleştirdiğimiz her işe aynı heyecan, istek ve pozitif enerjiyle yaklaşıyoruz. Hiç kaybetmek istemediğimiz amatör, bir o kadar da azimli ruhu canlı tutmaya gayret ediyoruz. Hizmet verdiğimiz tüm marka ve kuruluşların dinamiklerini, kültürünü ve hassasiyetlerini benimseyip bu nüanslara uygun servis vermek için kendimizi geliştiriyoruz..
        /// </summary>
        public static string Hakkimizda_bilgi_5 {
            get {
                return ResourceManager.GetString("Hakkimizda_bilgi_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HİZMETLERİMİZ.
        /// </summary>
        public static string HİZMETLERİMİZ {
            get {
                return ResourceManager.GetString("HİZMETLERİMİZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM.
        /// </summary>
        public static string İLETİŞİM {
            get {
                return ResourceManager.GetString("İLETİŞİM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM BİLGİLERİ.
        /// </summary>
        public static string iletisim_baslik {
            get {
                return ResourceManager.GetString("iletisim_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTANBUL ATATÜRK HAVAALANI VİP TRANSFER.
        /// </summary>
        public static string Istanbul_AtaturkHavaaalani {
            get {
                return ResourceManager.GetString("Istanbul_AtaturkHavaaalani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTANBUL SABİHA GÖKCEN VİP TRANSFER.
        /// </summary>
        public static string Istanbul_sabihagokcen_havaalani {
            get {
                return ResourceManager.GetString("Istanbul_sabihagokcen_havaalani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTANBUL TUR HİZMETLERİ.
        /// </summary>
        public static string Istanbul_Tur_Hızmetleri {
            get {
                return ResourceManager.GetString("Istanbul_Tur_Hızmetleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENÜLER.
        /// </summary>
        public static string Menuler {
            get {
                return ResourceManager.GetString("Menuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖZEL ŞÖFÖRLÜ MERCEDES VİTO KİRALAMA.
        /// </summary>
        public static string ozel_soforlu_mercedesvito_kiralama {
            get {
                return ResourceManager.GetString("ozel_soforlu_mercedesvito_kiralama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖZEL ŞOFÖRLÜ VİP TRANSFER.
        /// </summary>
        public static string Ozel_soforlu_transfer {
            get {
                return ResourceManager.GetString("Ozel_soforlu_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saatlik Transfer.
        /// </summary>
        public static string Saatlik_Transfer {
            get {
                return ResourceManager.GetString("Saatlik_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞEHİR DIŞI TURU.
        /// </summary>
        public static string Sehir_disi_turu {
            get {
                return ResourceManager.GetString("Sehir_disi_turu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞÖFÖRLÜ LÜKS ARAÇ KİRALAMA.
        /// </summary>
        public static string Şoforlu_luks_arackiralama {
            get {
                return ResourceManager.GetString("Şoforlu_luks_arackiralama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string TRANSFER {
            get {
                return ResourceManager.GetString("TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YENİ HAVAALANI VİP TRANSFER.
        /// </summary>
        public static string yeni_havaalani_transfer {
            get {
                return ResourceManager.GetString("yeni_havaalani_transfer", resourceCulture);
            }
        }
    }
}
