//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yolculuk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HizmetlerText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HizmetlerText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yolculuk.Resources.HizmetlerText", typeof(HizmetlerText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSINESS TANSFER.
        /// </summary>
        public static string BUSINESS_TANSFER {
            get {
                return ResourceManager.GetString("BUSINESS_TANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bankalara,gümrüklere,resmi dairelere evrak götürülmesi gibi işlerin Özel Transfer Hizmetleri birimimizce gerçekleştirilmektedir..
        /// </summary>
        public static string BUSINESS_TANSFER_bilgi_1 {
            get {
                return ResourceManager.GetString("BUSINESS_TANSFER_bilgi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misafirlerimizin talepleri doğrultusunda;tüm ziyaret planı kesinlikle gizli tutulur..
        /// </summary>
        public static string BUSINESS_TANSFER_bilgi_2 {
            get {
                return ResourceManager.GetString("BUSINESS_TANSFER_bilgi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTANBUL SABİHA GÖKÇEN VİP TRANSFER.
        /// </summary>
        public static string Istanbu_SABIHA_GOKCEN_HAVAALANİ {
            get {
                return ResourceManager.GetString("Istanbu_SABIHA_GOKCEN_HAVAALANİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gece yada gündüz.Profesyonel bir personelimiz sizleri veya misafirlerinizi bulunduğunuz konumdan alıyoruz.
        /// </summary>
        public static string Istanbu_SABIHA_GOKCEN_HAVAALANİ_bilgi_1 {
            get {
                return ResourceManager.GetString("Istanbu_SABIHA_GOKCEN_HAVAALANİ_bilgi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park yeri,otopark bedeli,trafik stresi ve yorgunluk hissetirmeden,valizlerinizi taşımanıza yardım ediyor ve en pratik yoldan sizi hava alanından hem karşılıyor hem de uğurluyoruz.Böylece sizde bir arkadaşınız yada yakınınız olmaksızın profesyonel bir hizmetle gitmek istediğiniz adrese veya havalimanına en hızlı şekilde ukaşıyoruz..
        /// </summary>
        public static string Istanbu_SABIHA_GOKCEN_HAVAALANİ_bilgi_2 {
            get {
                return ResourceManager.GetString("Istanbu_SABIHA_GOKCEN_HAVAALANİ_bilgi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTANBUL ATATÜRK VİP TRANSFER.
        /// </summary>
        public static string ISTANBUL_ATATURK_HAVAALANİ {
            get {
                return ResourceManager.GetString("ISTANBUL_ATATURK_HAVAALANİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gece yada gündüz.Profesyonel bir personelimiz sizleri veya misafirlerinizi bulunduğunuz konumdan alıyoruz.
        /// </summary>
        public static string ISTANBUL_ATATURK_HAVAALANİ_bilgi_1 {
            get {
                return ResourceManager.GetString("ISTANBUL_ATATURK_HAVAALANİ_bilgi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park yeri,otopark bedeli,trafik stresi ve yorgunluk hissetirmeden,valizlerinizi taşımanıza yardım ediyor ve en pratik yoldan sizi hava alanından hem karşılıyor hem de uğurluyoruz.Böylece sizde bir arkadaşınız yada yakınınız olmaksızın profesyonel bir hizmetle gitmek istediğiniz adrese veya havalimanına en hızlı şekilde ukaşıyoruz..
        /// </summary>
        public static string ISTANBUL_ATATURK_HAVAALANİ_bilgi_2 {
            get {
                return ResourceManager.GetString("ISTANBUL_ATATURK_HAVAALANİ_bilgi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTANBUL TUR HİZMETLERİ.
        /// </summary>
        public static string ISTANBUL_TUR_HIZMETLERI {
            get {
                return ResourceManager.GetString("ISTANBUL_TUR_HIZMETLERI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Dünyanın hayranlık duyduğu,bazılarının kıskandığı,kimilerinin onun için şiirler,şarkılar yazdığı İstanbul&apos;u misafirlerinize AYSEREN TRUZİM farkı ile tanıtıyor şehrin en güzel mekanlarını trafik park yeri sıkıntısı olmadan gezdiriyoruz.
        /// </summary>
        public static string ISTANBUL_TUR_HIZMETLERI_bilgi_1 {
            get {
                return ResourceManager.GetString("ISTANBUL_TUR_HIZMETLERI_bilgi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYSEREN TRUZİM tur hizmetleri ile İstanbul içi gezebileceğiniz bazı yerler aşağıda belirtimiştir.
        /// </summary>
        public static string ISTANBUL_TUR_HIZMETLERI_bilgi_2 {
            get {
                return ResourceManager.GetString("ISTANBUL_TUR_HIZMETLERI_bilgi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTANBUL YENİ HAVAALANI VİP TRANSFER.
        /// </summary>
        public static string ISTANBUL_YENİ_VIP_TRANSFER {
            get {
                return ResourceManager.GetString("ISTANBUL_YENİ_VIP_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gece yada gündüz.Profesyonel bir personelimiz sizleri veya misafirlerinizi bulunduğunuz konumdan alıyoruz.
        /// </summary>
        public static string ISTANBUL_YENİ_VIP_TRANSFER_bilgi_1 {
            get {
                return ResourceManager.GetString("ISTANBUL_YENİ_VIP_TRANSFER_bilgi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park yeri,otopark bedeli,trafik stresi ve yorgunluk hissetirmeden,valizlerinizi taşımanıza yardım ediyor ve en pratik yoldan sizi hava alanından hem karşılıyor hem de uğurluyoruz.Böylece sizde bir arkadaşınız yada yakınınız olmaksızın profesyonel bir hizmetle gitmek istediğiniz adrese veya havalimanına en hızlı şekilde ukaşıyoruz..
        /// </summary>
        public static string ISTANBUL_YENİ_VIP_TRANSFER_bilgi_2 {
            get {
                return ResourceManager.GetString("ISTANBUL_YENİ_VIP_TRANSFER_bilgi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖZEL GÜNLER İÇİN ŞÖFÖRLÜ VİP HİZMET.
        /// </summary>
        public static string ozel_gunler_icin_dugunhizmeti {
            get {
                return ResourceManager.GetString("ozel_gunler_icin_dugunhizmeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En özel gününüzü eşsiz kılmak için otel odası konforunda ulaşımın rahatlığını yaşamak istiyorsanız size herbiri bir diğerinden farklı,özel tasarım Lüks VIP Mercedes Vito araçlarımız ile çözümler üretmektedir..
        /// </summary>
        public static string ozel_gunler_icin_dugunhizmeti_bilgi_1 {
            get {
                return ResourceManager.GetString("ozel_gunler_icin_dugunhizmeti_bilgi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düğün,nişan,düğün alışverişi,gelin getirme,kına gecesi,sünnet düğünü gibi özel günlerinizde stresinizi azaltacak özel şoförlü,konforlu ve güvenli bir gelin arabasına kim hayır diyebilir.Gelin ve damat dışında diğer kişilerin de rahatlıkla konforlu seyahat edebileceği VİP gelin arabamızda Düğününüzün stresinden tek bir telefon ile kurtulun..
        /// </summary>
        public static string ozel_gunler_icin_dugunhizmeti_bilgi_2 {
            get {
                return ResourceManager.GetString("ozel_gunler_icin_dugunhizmeti_bilgi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖZEL ŞOFÖRLÜ VİP TRANSFER.
        /// </summary>
        public static string ozel_soforlu_vip_transfer {
            get {
                return ResourceManager.GetString("ozel_soforlu_vip_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konforlu ve keyifli bir yolculuk mu arıyorsunuz? Mercedes Vito ile V.I.P seyahatlere merhaba deyin!.
        /// </summary>
        public static string ozel_soforlu_vip_transfer_bilgi_1 {
            get {
                return ResourceManager.GetString("ozel_soforlu_vip_transfer_bilgi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vip araçlar ile transfer hizmetimiz dâhilinde, size profesyonel bir yolculuk yapma imkânı sunuyoruz. İhtiyaç duyduğunuz an, sadece bir telefon veya bir tık uzağınızdayız! Dilediğiniz aracı seçerek; konserlere, etkinliklere, otelinize, maçlara veya havalimanlarına sizler için sunmuş olduğumuz Vip araçlar ile özel transfer hizmetleri doğrultusunda gidebilirsiniz. Geçmiş hizmetlerimize yönelik referanslarımız, size sunduğumuz hizmetin bir güvencesidir..
        /// </summary>
        public static string ozel_soforlu_vip_transfer_bilgi_2 {
            get {
                return ResourceManager.GetString("ozel_soforlu_vip_transfer_bilgi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 gün 24 saat hizmetinize sunduğumuz Vip araçlar ile özel transfer hizmetlerimiz, havalimanı veya otel transferleriniz için profesyonel çözümler içerir. Uzman ve deneyimli kadromuz, sizlerin ihtiyacını en iyi şekilde karşılamak için çalışmaktadır. Müşteri temsilcilerimiz aracılığı ilekafanıza takılan her türlü soruyu sorabilir, rezervasyon iptal veya değişikliği için hızlıca iletişime geçebilirsiniz. Türkiye’nin birçok bölgesinde transfer hizmetlerinden yararlanabilirsiniz..
        /// </summary>
        public static string ozel_soforlu_vip_transfer_bilgi_3 {
            get {
                return ResourceManager.GetString("ozel_soforlu_vip_transfer_bilgi_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞEHİR DIŞI TUR HİZMETİ.
        /// </summary>
        public static string sehir_disi_tur_hizmeti {
            get {
                return ResourceManager.GetString("sehir_disi_tur_hizmeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Dünyanın hayranlık duyduğu,bazılarının kıskandığı,kimilerinin onun için şiirler,şarkılar yazdığı İstanbul&apos;u misafirlerinize AYSEREN TRUZİM farkı ile tanıtıyor şehrin en güzel mekanlarını trafik park yeri sıkıntısı olmadan gezdiriyoruz.
        /// </summary>
        public static string sehir_disi_tur_hizmeti_bilgi {
            get {
                return ResourceManager.GetString("sehir_disi_tur_hizmeti_bilgi", resourceCulture);
            }
        }
    }
}
