//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources.OgretmenPaneli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DosyaSinif {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DosyaSinif() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.OgretmenPaneli.DosyaSinif", typeof(DosyaSinif).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Ekle.
        /// </summary>
        public static string derseklebutton {
            get {
                return ResourceManager.GetString("derseklebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Kodu.
        /// </summary>
        public static string derskodu {
            get {
                return ResourceManager.GetString("derskodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dersleri Gör.
        /// </summary>
        public static string derslerigör {
            get {
                return ResourceManager.GetString("derslerigör", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Sil.
        /// </summary>
        public static string Derssil {
            get {
                return ResourceManager.GetString("Derssil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Dersler.
        /// </summary>
        public static string secilendersler {
            get {
                return ResourceManager.GetString("secilendersler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ders Oluştur.
        /// </summary>
        public static string yenidersoluştur {
            get {
                return ResourceManager.GetString("yenidersoluştur", resourceCulture);
            }
        }
    }
}
