//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPdfOdev.Resources.OgretmenPaneli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DosyaEkle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DosyaEkle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPdfOdev.Resources.OgretmenPaneli.DosyaEkle", typeof(DosyaEkle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Açıklama {
            get {
                return ResourceManager.GetString("Açıklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Kodu.
        /// </summary>
        public static string Derskodu {
            get {
                return ResourceManager.GetString("Derskodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Adi.
        /// </summary>
        public static string dosyaadi {
            get {
                return ResourceManager.GetString("dosyaadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Ekleme.
        /// </summary>
        public static string Dosyaekle {
            get {
                return ResourceManager.GetString("Dosyaekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya İşlemleri.
        /// </summary>
        public static string dosyaislemleri {
            get {
                return ResourceManager.GetString("dosyaislemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Seçiniz.
        /// </summary>
        public static string Dosyaseciniz {
            get {
                return ResourceManager.GetString("Dosyaseciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Yükleyen Kullanıcı.
        /// </summary>
        public static string dosyayükleyen {
            get {
                return ResourceManager.GetString("dosyayükleyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Anasayfa.
        /// </summary>
        public static string ogretmenAnasayfa {
            get {
                return ResourceManager.GetString("ogretmenAnasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Dosya Düzenle.
        /// </summary>
        public static string ogretmendosyaduzenle {
            get {
                return ResourceManager.GetString("ogretmendosyaduzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Dosya Gör.
        /// </summary>
        public static string ogretmendosyagör {
            get {
                return ResourceManager.GetString("ogretmendosyagör", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Dosyaları.
        /// </summary>
        public static string ogretmendosyalaribaslik {
            get {
                return ResourceManager.GetString("ogretmendosyalaribaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Dosya Sil.
        /// </summary>
        public static string ogretmendosyasil {
            get {
                return ResourceManager.GetString("ogretmendosyasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Dersler.
        /// </summary>
        public static string secilendersler {
            get {
                return ResourceManager.GetString("secilendersler", resourceCulture);
            }
        }
    }
}
